[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
pda_token_account = "3AD55KAgU7rd7zJByNS4gHL3w9hmb6YcWXvC7VmWbtYC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
